INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/_ping HTTP/1.1" 200 2
WARNING  root:conftest.py:124 Ryuk is enabled. This may not work with rootless podman.
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image testcontainers/ryuk:0.8.1
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create?name=testcontainers-ryuk-5eda5f7c-2a79-4e8e-8119-95dd5b61031a HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: be9bf828fb96
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/logs?stderr=0&stdout=1&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/logs?stderr=1&stdout=0&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: be9bf828fb96> with image testcontainers/ryuk:0.8.1 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/be9bf828fb9625b2f890ccf8f14b99cfc9d5606913796a23f84b409a7f3cbfd9/json HTTP/1.1" 200 None
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/34f38ccb161e627dc01f8a7554778be9fed2d5a0c787746d057934bf53166c48/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/34f38ccb161e627dc01f8a7554778be9fed2d5a0c787746d057934bf53166c48/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 34f38ccb161e
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/34f38ccb161e627dc01f8a7554778be9fed2d5a0c787746d057934bf53166c48/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/b8a22bc80e3d1a80a7a58363cff4b12a0bc17ea45d46438363fc6b9778c21f07/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/b8a22bc80e3d1a80a7a58363cff4b12a0bc17ea45d46438363fc6b9778c21f07/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/34f38ccb161e627dc01f8a7554778be9fed2d5a0c787746d057934bf53166c48/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/34f38ccb161e627dc01f8a7554778be9fed2d5a0c787746d057934bf53166c48?v=True&link=False&force=True HTTP/1.1" 204 0
DEBUG    root:base_image_test.py:85 OUTPUT> {"dir": "/bin", "count_scanned": 423, "unsatisfied": []}
DEBUG    root:base_image_test.py:85 	not a dynamic executable
DEBUG    root:base_image_test.py:85 Traceback (most recent call last):
DEBUG    root:base_image_test.py:85   File "<string>", line 5, in <module>
DEBUG    root:base_image_test.py:85   File "<string>", line 34, in check_elf_file
DEBUG    root:base_image_test.py:85   File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
DEBUG    root:base_image_test.py:85     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
DEBUG    root:base_image_test.py:85   File "/usr/lib64/python3.9/subprocess.py", line 528, in run
DEBUG    root:base_image_test.py:85     raise CalledProcessError(retcode, process.args,
DEBUG    root:base_image_test.py:85 subprocess.CalledProcessError: Command '['ldd', '/lib/rstudio-server/bin/quarto/bin/tools/x86_64/esbuild']' returned non-zero exit status 1.
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/998b9d264725513dd7706a3c0e380f02e14d9c88f61834f4d3bd88839ee95257/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/998b9d264725513dd7706a3c0e380f02e14d9c88f61834f4d3bd88839ee95257/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 998b9d264725
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/998b9d264725513dd7706a3c0e380f02e14d9c88f61834f4d3bd88839ee95257/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/cd4b57ff15603894312562610d0115aae9243f9674eef1a417b3f4af558cb981/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/cd4b57ff15603894312562610d0115aae9243f9674eef1a417b3f4af558cb981/json HTTP/1.1" 200 393
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/998b9d264725513dd7706a3c0e380f02e14d9c88f61834f4d3bd88839ee95257/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/998b9d264725513dd7706a3c0e380f02e14d9c88f61834f4d3bd88839ee95257?v=True&link=False&force=True HTTP/1.1" 204 0
DEBUG    root:base_image_test.py:117 Client Version: 4.17.12
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: aca5cdbaee0c
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/97425b7809e920c6114c9499541e2cb273829e414ed8da52dc430c7477f1f308/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/97425b7809e920c6114c9499541e2cb273829e414ed8da52dc430c7477f1f308/json HTTP/1.1" 200 416
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/79d85954f2af742eb0c1b9d1b01d9a02a9ed9d6e69d61f3f4b79b7c9d8bfb12f/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/79d85954f2af742eb0c1b9d1b01d9a02a9ed9d6e69d61f3f4b79b7c9d8bfb12f/json HTTP/1.1" 200 411
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/9395e6079ffb5157c4166ade973a0ec96463898d94eb2e228ada3c9799a6e9e9/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/9395e6079ffb5157c4166ade973a0ec96463898d94eb2e228ada3c9799a6e9e9/json HTTP/1.1" 200 406
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/1b9c46be2b526810b620374cbb4b1e29e4e653829055fb84ed98b32926faf7f8/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/1b9c46be2b526810b620374cbb4b1e29e4e653829055fb84ed98b32926faf7f8/json HTTP/1.1" 200 393
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/aca5cdbaee0cf99d4c6152028872d67629e8da1413e39cf932c4ee938145ae1f?v=True&link=False&force=True HTTP/1.1" 204 0
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 6a8355afd5e0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/c9cd55002b720c4c079e22eae90435f8e375ffd203a6fe244abf23d132b104d8/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/c9cd55002b720c4c079e22eae90435f8e375ffd203a6fe244abf23d132b104d8/json HTTP/1.1" 200 405
DEBUG    root:base_image_test.py:183 Collecting cowsay
  Downloading cowsay-6.1-py3-none-any.whl.metadata (5.6 kB)
Downloading cowsay-6.1-py3-none-any.whl (25 kB)
Installing collected packages: cowsay
Successfully installed cowsay-6.1

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/91559cd131ed0c3092e0e1457dfac9c76d0eac9a430559145f22ea82e293e03a/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/91559cd131ed0c3092e0e1457dfac9c76d0eac9a430559145f22ea82e293e03a/json HTTP/1.1" 200 412
DEBUG    root:base_image_test.py:187   ___________
| Hello world |
  ===========
           \
            \
              ^__^
              (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||

DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/6a8355afd5e04905346940014199eba457dbfe22fccdbd2c64f5251cc6a50335?v=True&link=False&force=True HTTP/1.1" 204 0
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/images/quay.io/opendatahub/workbench-images%40sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4/json HTTP/1.1" 200 None
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image <Image: ''>
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 52e3a4cbbbd6
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:172 {'Binds': [], 'ContainerIDFile': '', 'LogConfig': {'Type': 'journald', 'Config': None}, 'NetworkMode': 'bridge', 'PortBindings': {'8888/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '32805'}]}, 'RestartPolicy': {'Name': 'no', 'MaximumRetryCount': 0}, 'AutoRemove': False, 'VolumeDriver': '', 'VolumesFrom': None, 'ConsoleSize': [0, 0], 'Annotations': {'io.container.manager': 'libpod', 'org.opencontainers.image.stopSignal': '15', 'org.systemd.property.KillSignal': '15', 'org.systemd.property.TimeoutStopUSec': 'uint64 10000000'}, 'CapAdd': [], 'CapDrop': [], 'CgroupnsMode': '', 'Dns': [], 'DnsOptions': [], 'DnsSearch': [], 'ExtraHosts': [], 'GroupAdd': ['0'], 'IpcMode': 'shareable', 'Cgroup': '', 'Links': None, 'OomScoreAdj': 200, 'PidMode': 'private', 'Privileged': False, 'PublishAllPorts': False, 'ReadonlyRootfs': False, 'SecurityOpt': [], 'Tmpfs': {'/opt/app-root/src': 'rw,rprivate,nosuid,nodev'}, 'UTSMode': 'private', 'UsernsMode': '', 'ShmSize': 65536000, 'Runtime': 'oci', 'Isolation': '', 'CpuShares': 0, 'Memory': 0, 'NanoCpus': 0, 'CgroupParent': 'user.slice', 'BlkioWeight': 0, 'BlkioWeightDevice': None, 'BlkioDeviceReadBps': None, 'BlkioDeviceWriteBps': None, 'BlkioDeviceReadIOps': None, 'BlkioDeviceWriteIOps': None, 'CpuPeriod': 0, 'CpuQuota': 0, 'CpuRealtimePeriod': 0, 'CpuRealtimeRuntime': 0, 'CpusetCpus': '', 'CpusetMems': '', 'Devices': [], 'DeviceCgroupRules': None, 'DeviceRequests': None, 'MemoryReservation': 0, 'MemorySwap': 0, 'MemorySwappiness': 0, 'OomKillDisable': False, 'PidsLimit': 2048, 'Ulimits': [{'Name': 'RLIMIT_NOFILE', 'Hard': 524288, 'Soft': 524288}, {'Name': 'RLIMIT_NPROC', 'Hard': 255425, 'Soft': 255425}], 'CpuCount': 0, 'CpuPercent': 0, 'IOMaximumIOps': 0, 'IOMaximumBandwidth': 0, 'MaskedPaths': None, 'ReadonlyPaths': None}
DEBUG    root:docker_utils.py:61 Adding src='/tmp/tmp8t1u_b2r/script.R' to archive dst='/opt/app-root/src'
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "PUT /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e/archive?path=%2Fopt%2Fapp-root%2Fsrc HTTP/1.1" 500 199
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/52e3a4cbbbd602adbb5b148eca002b8924a3ff0c3e1dcfc2a71e3ae83f172e8e?v=True&link=False&force=True HTTP/1.1" 204 0
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/images/quay.io/opendatahub/workbench-images%40sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4/json HTTP/1.1" 200 None
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image <Image: ''>
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 6c4b1914195a
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:172 {'Binds': [], 'ContainerIDFile': '', 'LogConfig': {'Type': 'journald', 'Config': None}, 'NetworkMode': 'bridge', 'PortBindings': {'8888/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '39645'}]}, 'RestartPolicy': {'Name': 'no', 'MaximumRetryCount': 0}, 'AutoRemove': False, 'VolumeDriver': '', 'VolumesFrom': None, 'ConsoleSize': [0, 0], 'Annotations': {'io.container.manager': 'libpod', 'org.opencontainers.image.stopSignal': '15', 'org.systemd.property.KillSignal': '15', 'org.systemd.property.TimeoutStopUSec': 'uint64 10000000'}, 'CapAdd': [], 'CapDrop': [], 'CgroupnsMode': '', 'Dns': [], 'DnsOptions': [], 'DnsSearch': [], 'ExtraHosts': [], 'GroupAdd': ['0'], 'IpcMode': 'shareable', 'Cgroup': '', 'Links': None, 'OomScoreAdj': 200, 'PidMode': 'private', 'Privileged': False, 'PublishAllPorts': False, 'ReadonlyRootfs': False, 'SecurityOpt': [], 'Tmpfs': {'/opt/app-root/src': 'rw,rprivate,nosuid,nodev'}, 'UTSMode': 'private', 'UsernsMode': '', 'ShmSize': 65536000, 'Runtime': 'oci', 'Isolation': '', 'CpuShares': 0, 'Memory': 0, 'NanoCpus': 0, 'CgroupParent': 'user.slice', 'BlkioWeight': 0, 'BlkioWeightDevice': None, 'BlkioDeviceReadBps': None, 'BlkioDeviceWriteBps': None, 'BlkioDeviceReadIOps': None, 'BlkioDeviceWriteIOps': None, 'CpuPeriod': 0, 'CpuQuota': 0, 'CpuRealtimePeriod': 0, 'CpuRealtimeRuntime': 0, 'CpusetCpus': '', 'CpusetMems': '', 'Devices': [], 'DeviceCgroupRules': None, 'DeviceRequests': None, 'MemoryReservation': 0, 'MemorySwap': 0, 'MemorySwappiness': 0, 'OomKillDisable': False, 'PidsLimit': 2048, 'Ulimits': [{'Name': 'RLIMIT_NOFILE', 'Hard': 524288, 'Soft': 524288}, {'Name': 'RLIMIT_NPROC', 'Hard': 255425, 'Soft': 255425}], 'CpuCount': 0, 'CpuPercent': 0, 'IOMaximumIOps': 0, 'IOMaximumBandwidth': 0, 'MaskedPaths': None, 'ReadonlyPaths': None}
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 6c4b1914195a> with image <Image: ''> to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 6c4b1914195a> with image <Image: ''> to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 6c4b1914195a> with image <Image: ''> to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/json HTTP/1.1" 200 None
DEBUG    root:rstudio_test.py:151 Running command >>> {"cmd": "/usr/bin/R --quiet --no-echo -e 'Sys.getenv(\"http_proxy\")'"}
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/83b3fd9796a3760733d173290cf96d8195fc418204a1a7211668f41f7a508b5c/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/83b3fd9796a3760733d173290cf96d8195fc418204a1a7211668f41f7a508b5c/json HTTP/1.1" 200 434
DEBUG    root:rstudio_test.py:154 Command execution finished >>> {"rc": 0, "result": "[1] \"http://localhost:8080\"\n"}
DEBUG    root:rstudio_test.py:151 Running command >>> {"cmd": "/usr/bin/R --quiet --no-echo -e 'Sys.getenv(\"https_proxy\")'"}
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/0ae14c41f5a7e984987461d13f87e0265bff15ecf2a212f6f70eea4549727c7f/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/0ae14c41f5a7e984987461d13f87e0265bff15ecf2a212f6f70eea4549727c7f/json HTTP/1.1" 200 435
DEBUG    root:rstudio_test.py:154 Command execution finished >>> {"rc": 0, "result": "[1] \"https://localhost:8443\"\n"}
DEBUG    root:rstudio_test.py:151 Running command >>> {"cmd": "/usr/bin/R --quiet --no-echo -e 'Sys.getenv(\"no_proxy\")'"}
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/exec HTTP/1.1" 201 74
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/exec/72930a0ffa4b0c7dd0351bd2f64fecee1cf78f7bd56fb447e4f3312e7ca5a892/start HTTP/1.1" 101 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/exec/72930a0ffa4b0c7dd0351bd2f64fecee1cf78f7bd56fb447e4f3312e7ca5a892/json HTTP/1.1" 200 432
DEBUG    root:rstudio_test.py:154 Command execution finished >>> {"rc": 0, "result": "[1] \"google.com\"\n"}
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/6c4b1914195ada6987107b1c98a99f07b034d969dc533580db2c0731ede462fc?v=True&link=False&force=True HTTP/1.1" 204 0
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/images/quay.io/opendatahub/workbench-images%40sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4/json HTTP/1.1" 200 None
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 12bfaf8b157c
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:172 {'Binds': [], 'ContainerIDFile': '', 'LogConfig': {'Type': 'journald', 'Config': None}, 'NetworkMode': 'bridge', 'PortBindings': {'8888/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '46513'}]}, 'RestartPolicy': {'Name': 'no', 'MaximumRetryCount': 0}, 'AutoRemove': False, 'VolumeDriver': '', 'VolumesFrom': None, 'ConsoleSize': [0, 0], 'Annotations': {'io.container.manager': 'libpod', 'org.opencontainers.image.stopSignal': '15', 'org.systemd.property.KillSignal': '15', 'org.systemd.property.TimeoutStopUSec': 'uint64 10000000'}, 'CapAdd': [], 'CapDrop': [], 'CgroupnsMode': '', 'Dns': [], 'DnsOptions': [], 'DnsSearch': [], 'ExtraHosts': [], 'GroupAdd': ['0'], 'IpcMode': 'shareable', 'Cgroup': '', 'Links': None, 'OomScoreAdj': 200, 'PidMode': 'private', 'Privileged': False, 'PublishAllPorts': False, 'ReadonlyRootfs': False, 'SecurityOpt': [], 'Tmpfs': {'/opt/app-root/src': 'rw,rprivate,nosuid,nodev'}, 'UTSMode': 'private', 'UsernsMode': '', 'ShmSize': 65536000, 'Runtime': 'oci', 'Isolation': '', 'CpuShares': 0, 'Memory': 0, 'NanoCpus': 0, 'CgroupParent': 'user.slice', 'BlkioWeight': 0, 'BlkioWeightDevice': None, 'BlkioDeviceReadBps': None, 'BlkioDeviceWriteBps': None, 'BlkioDeviceReadIOps': None, 'BlkioDeviceWriteIOps': None, 'CpuPeriod': 0, 'CpuQuota': 0, 'CpuRealtimePeriod': 0, 'CpuRealtimeRuntime': 0, 'CpusetCpus': '', 'CpusetMems': '', 'Devices': [], 'DeviceCgroupRules': None, 'DeviceRequests': None, 'MemoryReservation': 0, 'MemorySwap': 0, 'MemorySwappiness': 0, 'OomKillDisable': False, 'PidsLimit': 2048, 'Ulimits': [{'Name': 'RLIMIT_NOFILE', 'Hard': 524288, 'Soft': 524288}, {'Name': 'RLIMIT_NPROC', 'Hard': 255425, 'Soft': 255425}], 'CpuCount': 0, 'CpuPercent': 0, 'IOMaximumIOps': 0, 'IOMaximumBandwidth': 0, 'MaskedPaths': None, 'ReadonlyPaths': None}
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 12bfaf8b157c> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 12bfaf8b157c> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 12bfaf8b157c> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 12bfaf8b157c> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 12bfaf8b157c> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/logs?stderr=0&stdout=1&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/logs?stderr=1&stdout=0&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 44#44: using the "epoll" event method
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 44#44: nginx/1.24.0
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 44#44: built by gcc 11.4.1 20231218 (Red Hat 11.4.1-3) (GCC) 
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 44#44: OS: Linux 6.12.11-200.fc41.x86_64
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 44#44: getrlimit(RLIMIT_NOFILE): 524288:524288
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 59#59: start worker processes
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [notice] 59#59: start worker process 60
DEBUG    root:workbench_image_test.py:200 10.88.0.82 - - [24/Feb/2025:09:43:49 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:49 [error] 60#60: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.88.0.82, server: ${base_url}, request: "GET /rstudio/ HTTP/1.1", upstream: "http://127.0.0.1:8787/", host: "localhost:46513"
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:49,682 INFO supervisord started with pid 4
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --server-working-dir=/opt/app-root/src --auth-none=1 --www-frame-origin=same --www-port=8787 --www-verify-user-agent=0 --rsession-which-r=/usr/bin/R --secure-cookie-key-file=/tmp/tmpu62n7u4c --server-user=1000 --rsession-path=/opt/app-root/bin/rsession.sh --server-data-dir=/tmp/tmpkcbjpzd9 --database-config-file=/tmp/tmpkcbjpzd9/tmpgrfi3xte
DEBUG    root:workbench_image_test.py:200 Running command: /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --server-working-dir=/opt/app-root/src --auth-none=1 --www-frame-origin=same --www-port=8787 --www-verify-user-agent=0 --rsession-which-r=/usr/bin/R --secure-cookie-key-file=/tmp/tmpu62n7u4c --server-user=1000 --rsession-path=/opt/app-root/bin/rsession.sh --server-data-dir=/tmp/tmpkcbjpzd9 --database-config-file=/tmp/tmpkcbjpzd9/tmpgrfi3xte
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:50,685 INFO spawned: 'fcgiwrap' with pid 428
DEBUG    root:workbench_image_test.py:200 10.88.0.82 - - [24/Feb/2025:09:43:50 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 10.88.0.82 - - [24/Feb/2025:09:43:50 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:51,686 INFO success: fcgiwrap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
DEBUG    root:workbench_image_test.py:208 Waived message: '2025/02/24 09:43:49 [error] 60#60: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.88.0.82, server: ${base_url}, request: "GET /rstudio/ HTTP/1.1", upstream: "http://127.0.0.1:8787/", host: "localhost:46513"'
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/12bfaf8b157cc20f52a19e1275a6f275fea405d3847daffeec14173c7b747ee6?v=True&link=False&force=True HTTP/1.1" 204 0
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/images/quay.io/opendatahub/workbench-images%40sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4/json HTTP/1.1" 200 None
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
INFO     testcontainers.core.container:container.py:98 Pulling image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:125 Container started: 552b5d2d29f6
INFO     testcontainers.core.docker_client:docker_client.py:66 using host unix:///run/user/4218382/podman/podman.sock
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    docker.utils.config:config.py:21 Trying paths: ['/home/froman/.docker/config.json', '/home/froman/.dockercfg']
DEBUG    docker.utils.config:config.py:28 No config file found
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 947
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:172 {'Binds': [], 'ContainerIDFile': '', 'LogConfig': {'Type': 'journald', 'Config': None}, 'NetworkMode': 'bridge', 'PortBindings': {'8888/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '34841'}]}, 'RestartPolicy': {'Name': 'no', 'MaximumRetryCount': 0}, 'AutoRemove': False, 'VolumeDriver': '', 'VolumesFrom': None, 'ConsoleSize': [0, 0], 'Annotations': {'io.container.manager': 'libpod', 'org.opencontainers.image.stopSignal': '15', 'org.systemd.property.KillSignal': '15', 'org.systemd.property.TimeoutStopUSec': 'uint64 10000000'}, 'CapAdd': [], 'CapDrop': [], 'CgroupnsMode': '', 'Dns': [], 'DnsOptions': [], 'DnsSearch': [], 'ExtraHosts': [], 'GroupAdd': ['0'], 'IpcMode': 'shareable', 'Cgroup': '', 'Links': None, 'OomScoreAdj': 200, 'PidMode': 'private', 'Privileged': False, 'PublishAllPorts': False, 'ReadonlyRootfs': False, 'SecurityOpt': [], 'Tmpfs': {'/opt/app-root/src': 'rw,rprivate,nosuid,nodev'}, 'UTSMode': 'private', 'UsernsMode': '', 'ShmSize': 65536000, 'Runtime': 'oci', 'Isolation': '', 'CpuShares': 0, 'Memory': 0, 'NanoCpus': 0, 'CgroupParent': 'user.slice', 'BlkioWeight': 0, 'BlkioWeightDevice': None, 'BlkioDeviceReadBps': None, 'BlkioDeviceWriteBps': None, 'BlkioDeviceReadIOps': None, 'BlkioDeviceWriteIOps': None, 'CpuPeriod': 0, 'CpuQuota': 0, 'CpuRealtimePeriod': 0, 'CpuRealtimeRuntime': 0, 'CpusetCpus': '', 'CpusetMems': '', 'Devices': [], 'DeviceCgroupRules': None, 'DeviceRequests': None, 'MemoryReservation': 0, 'MemorySwap': 0, 'MemorySwappiness': 0, 'OomKillDisable': False, 'PidsLimit': 2048, 'Ulimits': [{'Name': 'RLIMIT_NOFILE', 'Hard': 524288, 'Soft': 524288}, {'Name': 'RLIMIT_NPROC', 'Hard': 255425, 'Soft': 255425}], 'CpuCount': 0, 'CpuPercent': 0, 'IOMaximumIOps': 0, 'IOMaximumBandwidth': 0, 'MaskedPaths': None, 'ReadonlyPaths': None}
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 552b5d2d29f6> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 552b5d2d29f6> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 552b5d2d29f6> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 552b5d2d29f6> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
INFO     testcontainers.core.waiting_utils:waiting_utils.py:52 Waiting for container <Container: 552b5d2d29f6> with image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4 to be ready ...
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/logs?stderr=0&stdout=1&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/logs?stderr=1&stdout=0&timestamps=0&follow=0&tail=all HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/json HTTP/1.1" 200 None
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:54,683 INFO supervisord started with pid 4
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 42#42: using the "epoll" event method
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 42#42: nginx/1.24.0
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 42#42: built by gcc 11.4.1 20231218 (Red Hat 11.4.1-3) (GCC) 
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 42#42: OS: Linux 6.12.11-200.fc41.x86_64
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 42#42: getrlimit(RLIMIT_NOFILE): 524288:524288
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 59#59: start worker processes
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [notice] 59#59: start worker process 60
DEBUG    root:workbench_image_test.py:200 10.88.0.83 - - [24/Feb/2025:09:43:54 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 2025/02/24 09:43:54 [error] 60#60: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.88.0.83, server: ${base_url}, request: "GET /rstudio/ HTTP/1.1", upstream: "http://127.0.0.1:8787/", host: "localhost:34841"
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --server-working-dir=/opt/app-root/src --auth-none=1 --www-frame-origin=same --www-port=8787 --www-verify-user-agent=0 --rsession-which-r=/usr/bin/R --secure-cookie-key-file=/tmp/tmplsh3hd_9 --server-user=1000 --rsession-path=/opt/app-root/bin/rsession.sh --server-data-dir=/tmp/tmpy1uqgmv8 --database-config-file=/tmp/tmpy1uqgmv8/tmpt97mm_cs
DEBUG    root:workbench_image_test.py:200 Running command: /usr/lib/rstudio-server/bin/rserver --server-daemonize=0 --server-working-dir=/opt/app-root/src --auth-none=1 --www-frame-origin=same --www-port=8787 --www-verify-user-agent=0 --rsession-which-r=/usr/bin/R --secure-cookie-key-file=/tmp/tmplsh3hd_9 --server-user=1000 --rsession-path=/opt/app-root/bin/rsession.sh --server-data-dir=/tmp/tmpy1uqgmv8 --database-config-file=/tmp/tmpy1uqgmv8/tmpt97mm_cs
DEBUG    root:workbench_image_test.py:200 TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/etc/rstudio/logging.conf'. Logging to '/opt/app-root/src/.local/share/rstudio/log/rserver.log'.
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:55,685 INFO spawned: 'fcgiwrap' with pid 418
DEBUG    root:workbench_image_test.py:200 10.88.0.83 - - [24/Feb/2025:09:43:55 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 10.88.0.83 - - [24/Feb/2025:09:43:56 +0000] "GET / HTTP/1.1" 302 145 "-" "Python-urllib/3.12" "-"
DEBUG    root:workbench_image_test.py:200 2025-02-24 09:43:56,687 INFO success: fcgiwrap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
DEBUG    root:workbench_image_test.py:208 Waived message: '2025/02/24 09:43:54 [error] 60#60: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.88.0.83, server: ${base_url}, request: "GET /rstudio/ HTTP/1.1", upstream: "http://127.0.0.1:8787/", host: "localhost:34841"'
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb/stop?t=0 HTTP/1.1" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "DELETE /v1.41/containers/552b5d2d29f6f507883feff2ef8222ec70478731f5c6ff95a1c2814c449671bb?v=True&link=False&force=True HTTP/1.1" 204 0
